#!/bin/bash

echo Creating Partitions...
parted /dev/sda
mklabel gpt
unit mib
mkpart primary 1 3
name 1 grub
set 1 bios_grub on
mkpart primary 3 131
name 2 boot
set 2 boot on
mkpart primary 131 643
name 3 swap
mkpart primary 643 -1
name 4 rootfs

echo creating filesystems...
mkfs.ext2 /dev/sda2
mkfs.ext4 /dev/sda4

echo mounting partitions...

mount /dev/sda4 /mnt/gentoo
mkswap /dev/sda3 swapon /dev/sda3
chmod 1777 /var/tmp

echo stage3..
cd /mnt/gentoo
