#!/bin/bash

echo Creating Partitions...
parted /dev/sda << END
mklabel gpt
unit mib
mkpart primary 1 3
name 1 grub
set 1 bios_grub on
mkpart primary 3 131
name 2 boot
set 2 boot on
mkpart primary 131 643
name 3 swap
mkpart primary 643 -1
name 4 rootfs
quit
;
END

echo creating filesystems...
mkfs.ext2 /dev/sda2
mkfs.ext4 /dev/sda4

echo mounting partitions...

mount /dev/sda4 /mnt/gentoo
mkswap /dev/sda3 swapon /dev/sda3
chmod 1777 /var/tmp

echo stage3..
cd /mnt/gentoo 
sleep 1s
wget http://distfiles.gentoo.org/releases/amd64/autobuilds/20190814T214502Z/stage3-amd64-20190814T214502Z.tar.xz
sleep 1s
cd /mnt/gentoo
tar xpvf stage3-*.tar.xz --xattrs-include='*.*' --numeric-owner
sleep 1s
cd /mnt/gentoo
echo MAKEOPTS='"-j2"' >> etc/portage/make.conf 
sleep 1s
cd /mnt/gentoo

cp --dereference /etc/resolv.conf /mnt/gentoo/etc/

mount --types proc /proc /mnt/gentoo/proc
sleep 2s
mount --rbind /sys /mnt/gentoo/sys
sleep 2s
mount --make-rslave /mnt/gentoo/sys
sleep 2s
mount --rbind /dev /mnt/gentoo/dev
sleep 2s
mount --make-rslave /mnt/gentoo/dev
sleep 2s
chroot /mnt/gentoo /bin/bash << END
sleep 2s
source /etc/profile
sleep 1s
#!/bin/bash
sleep 2s 
export PS1="(chroot) ${PS1}"
sleep 2s
mount /dev/sda2 /boot
sleep 2s
emerge-webrsync
eselect profile set 1
sleep 2s
emerge  --verbose --update --deep --newuse @world
sleep 2s
env-update && source /etc/profile && export PS1="(chroot) ${PS1}"
sleep 2s
ls -l /usr/src/linux
 echo "sys-apps/util-linux static-libs" > /etc/portage/package.use/genkernel
emerge --autounmask y sys-kernel/genkernel
sleep 2s
echo /dev/sda2   /boot        ext2    defaults,noatime     0 2 >> /etc/fstab
echo /dev/sda3   none         swap    sw                   0 0 >> /etc/fstab
echo /dev/sda4   /            ext4    noatime              0 1 >> /etc/fstab
echo /dev/cdrom  /mnt/cdrom   auto    noauto,user          0 0 >> /etc/fstab

sleep 1s 
genkernel all


END
